-- scripts/rehearsal_m2_evidence.sql — LOCAL REHEARSAL ONLY (run via
-- scripts/rehearsal_m2_evidence.sh). Captures the REAL `venue.get_door_manifest`
-- output for the SCANNER-CONTRACT-v1 evidence file
-- (tests/fixtures/m2-rehearsal-evidence.json), inside one transaction that is
-- ROLLED BACK — the rehearsal database is left exactly as it was.
-- Requires the tap helper schema (000_helpers.sql) — the runner applies it.
\set ON_ERROR_STOP on
\pset format unaligned
\pset tuples_only on
\pset pager off
BEGIN;
CREATE TEMP TABLE ev (k text PRIMARY KEY, v jsonb) ON COMMIT DROP;
-- inputs from the runner (psql variables are not expanded inside a DO body)
CREATE TEMP TABLE ev_in (k text PRIMARY KEY, v text) ON COMMIT DROP;
INSERT INTO ev_in VALUES ('m1_public_pem', :'M1_PUBLIC_PEM');
GRANT INSERT, SELECT ON ev TO authenticated, anon, service_role; -- the tap.login() role switches write into it too
DO $body$
DECLARE
  v_org uuid; v_venue uuid; v_e uuid; v_s uuid; v_tt uuid; v_b uuid; v_k uuid; v_m1 uuid; v_m2 uuid;
  v_atom uuid; v_err text; v_dev uuid; v_dsid uuid; v_secret text; v_mint jsonb; v_mint2 jsonb;
  v_pem text; v_e2 uuid; v_venue2 uuid; v_g_active uuid; v_g_rotating uuid; v_g_revoked uuid; v_e_future uuid; v_e_other uuid; v_v_venue uuid; v_v_other uuid; v_ctx jsonb;
BEGIN
  PERFORM tap.seed_core();
  PERFORM tap.login(tap.seller());
  v_org := (kernel.create_organization('EV Co','EV Co','ev-o') ->> 'org_id')::uuid;
  PERFORM tap.logout();
  UPDATE kernel.organization SET status='approved' WHERE org_id = v_org;
  PERFORM tap.login(tap.seller());
  v_venue := (catalog.create_venue(v_org,'EV Hall','wynwood',NULL,'ev-v') ->> 'venue_id')::uuid;
  PERFORM tap.logout();
  PERFORM tap.login(tap.admin_user());
  PERFORM catalog.approve_venue(v_venue,'approved','miami_gate','ev-a');
  PERFORM tap.logout();
  INSERT INTO catalog.platform_config (key, version, value, visibility) VALUES ('feature.native_issuance_enabled', 2, 'true'::jsonb, 'public');
  INSERT INTO catalog.platform_config (key, version, value, visibility) VALUES ('feature.native_scanning_enabled', 2, 'true'::jsonb, 'public');
  INSERT INTO venue.staff_role (venue_id, identity_id, role, granted_by)
  VALUES (v_venue, tap.seller(), 'venue_manager', tap.admin_user()), (v_venue, tap.other_user(), 'venue_scanner', tap.admin_user()) ON CONFLICT DO NOTHING;
  PERFORM tap.login(tap.seller());
  v_e := (catalog.create_event(v_venue,'EV Night', jsonb_build_object('starts_at',(now()+interval '9 days')::text,'ends_at',(now()+interval '9 days 5 hours')::text),'ev-e') ->> 'event_id')::uuid;
  SELECT session_id INTO v_s FROM catalog.event_session WHERE event_id = v_e;
  v_tt := (venue.create_ticket_type(v_e,'admission','GA',5000,'public','ev-tt') ->> 'ticket_type_id')::uuid;
  v_b := (venue.create_inventory_batch(v_tt, v_s, 'comp', 100, 0, 'ev-b') ->> 'batch_id')::uuid;
  v_e2 := (catalog.create_event(v_venue,'EV Other', jsonb_build_object('starts_at',(now()+interval '9 days')::text,'ends_at',(now()+interval '9 days 5 hours')::text),'ev-e2') ->> 'event_id')::uuid;
  v_venue2 := (catalog.create_venue(v_org,'EV Annex','wynwood',NULL,'ev-v2') ->> 'venue_id')::uuid;
  v_dev := (venue.register_scan_device(v_venue, 'scanner-ev', 'ev-dev') ->> 'device_id')::uuid;
  PERFORM venue.create_door_pin(v_venue, v_s, 'front', 'pin-ev', (now()+interval '1 day'), 'ev-pin');
  PERFORM tap.logout();
  INSERT INTO kernel.signing_key (scope, event_id, public_key, kms_handle_ref, status, not_before, algorithm)
  VALUES ('per_event', v_e, 'PUBKEY-EV', 'kms-ev', 'active', now(), 'ES256') RETURNING key_id INTO v_k;
  -- keyring (114 evidence). g_active's public_key is a REAL P-256 SPKI PEM generated by the
  -- runner for this capture (private half used once to sign the artifact, then discarded).
  SELECT v INTO v_pem FROM ev_in WHERE k = 'm1_public_pem';
  INSERT INTO kernel.signing_key (scope, public_key, kms_handle_ref, status, not_before, not_after, algorithm)
  VALUES ('global', v_pem, 'arn:aws:kms:us-east-1:000000000000:key/0b0b0b0b-0b0b-4b0b-8b0b-0b0b0b0b0b01', 'active', now() - interval '1 hour', NULL, 'ES256') RETURNING key_id INTO v_g_active;
  INSERT INTO kernel.signing_key (scope, public_key, kms_handle_ref, status, not_before, not_after, algorithm)
  VALUES ('global', v_pem, 'arn:aws:kms:us-east-1:000000000000:key/0b0b0b0b-0b0b-4b0b-8b0b-0b0b0b0b0b02', 'rotating', now() - interval '30 days', now() - interval '1 day', 'ES256') RETURNING key_id INTO v_g_rotating;
  INSERT INTO kernel.signing_key (scope, public_key, kms_handle_ref, status, not_before, not_after, algorithm)
  VALUES ('global', v_pem, 'arn:aws:kms:us-east-1:000000000000:key/0b0b0b0b-0b0b-4b0b-8b0b-0b0b0b0b0b03', 'revoked', now() - interval '60 days', now() - interval '30 days', 'ES256') RETURNING key_id INTO v_g_revoked;
  INSERT INTO kernel.signing_key (scope, event_id, public_key, kms_handle_ref, status, not_before, algorithm)
  VALUES ('per_event', v_e, v_pem, 'kms-ev-future', 'rotating', now() + interval '1 day', 'ES256') RETURNING key_id INTO v_e_future;   -- one ACTIVE per event (signing_key_active_event_uq)
  INSERT INTO kernel.signing_key (scope, event_id, public_key, kms_handle_ref, status, not_before, algorithm)
  VALUES ('per_event', v_e2, v_pem, 'kms-ev-other', 'active', now() - interval '1 hour', 'ES256') RETURNING key_id INTO v_e_other;
  INSERT INTO kernel.signing_key (scope, venue_id, public_key, kms_handle_ref, status, not_before, algorithm)
  VALUES ('per_venue', v_venue, v_pem, 'kms-ev-venue', 'active', now() - interval '1 hour', 'ES256') RETURNING key_id INTO v_v_venue;
  INSERT INTO kernel.signing_key (scope, venue_id, public_key, kms_handle_ref, status, not_before, algorithm)
  VALUES ('per_venue', v_venue2, v_pem, 'kms-ev-venue2', 'active', now() - interval '1 hour', 'ES256') RETURNING key_id INTO v_v_other;
  PERFORM kernel.issue_ticket_atoms(jsonb_build_object('session_id',v_s,'org_id',v_org,'ticket_type_id',v_tt,'batch_id',v_b,
    'owner_id',tap.buyer(),'quantity',3,'cause','comp','cause_ref',gen_random_uuid(),'signing_key_id',v_k),'ev-m');
  PERFORM tap.login(tap.seller());
  v_m1 := (venue.open_door_manifest(v_s,'doors_open','ev-d1') ->> 'manifest_id')::uuid;
  PERFORM tap.logout();

  -- door session (113 machine path). The SECRET is used in-flight only and is
  -- NEVER written into the evidence table (the fixture is committed to the repo).
  PERFORM tap.login_service();
  v_mint := venue.mint_door_session(v_venue, v_s, v_dev, 'pin-ev', 'ev-mint');
  PERFORM tap.logout();
  v_dsid := (v_mint ->> 'door_session_id')::uuid; v_secret := v_mint ->> 'secret';
  INSERT INTO ev VALUES ('ids', jsonb_build_object('session_id', v_s, 'venue_id', v_venue, 'event_id', v_e, 'signing_key_id', v_k, 'manifest_id', v_m1,
                                                   'device_id', v_dev, 'door_session_id', v_dsid));
  INSERT INTO ev SELECT 'stored_header', jsonb_build_object('manifest_id', manifest_id, 'manifest_version', manifest_version, 'session_id', session_id,
     'opened_at', opened_at, 'not_after', not_after, 'manifest_digest', manifest_digest, 'status', status) FROM venue.door_manifest WHERE manifest_id = v_m1;

  PERFORM tap.login(tap.other_user());
  INSERT INTO ev VALUES ('open_full', venue.get_door_manifest(v_s, 0));
  PERFORM tap.logout();
  PERFORM tap.login_service();
  INSERT INTO ev VALUES ('door_full', venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0));
  -- 114: M1 for the door device + the manifest-signing key identity
  INSERT INTO ev VALUES ('door_keys', venue.get_signing_keys_door(v_s, v_dsid, v_secret, v_dev));
  INSERT INTO ev VALUES ('signing_key_ids', jsonb_build_object('g_active', v_g_active, 'g_rotating', v_g_rotating, 'g_revoked', v_g_revoked,
     'e_active', v_k, 'e_future', v_e_future, 'e_other_unrelated', v_e_other, 'v_venue', v_v_venue, 'v_other_unrelated', v_v_other));
  v_ctx := venue.get_manifest_signing_context();
  -- the handle is NEVER written into the committed fixture: only its presence/shape is recorded.
  INSERT INTO ev VALUES ('manifest_signing_context', (v_ctx - 'kms_handle_ref') || jsonb_build_object(
     'kms_handle_ref_present', v_ctx ? 'kms_handle_ref',
     'kms_handle_ref_is_key_arn', (v_ctx ->> 'kms_handle_ref') ~ '^arn:aws:kms:[a-z]{2}(-[a-z]+)+-[0-9]:[0-9]{12}:key/[0-9a-f-]{36}$'));
  BEGIN PERFORM venue.get_signing_keys_door(v_s, v_dsid, 'not-the-secret', v_dev); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_keys_wrong_token', to_jsonb(v_err));
  BEGIN PERFORM venue.get_signing_keys_door(gen_random_uuid(), v_dsid, v_secret, v_dev); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_keys_wrong_session', to_jsonb(v_err));
  BEGIN PERFORM venue.get_signing_keys_door(v_s, gen_random_uuid(), '', gen_random_uuid()); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_keys_service_role_no_credentials', to_jsonb(v_err));
  PERFORM tap.logout();
  PERFORM tap.login_anon();
  BEGIN PERFORM venue.get_signing_keys_door(v_s, v_dsid, v_secret, v_dev); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_keys_anon_direct', to_jsonb(v_err));
  BEGIN PERFORM venue.get_manifest_signing_context(); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('manifest_signing_context_anon', to_jsonb(v_err));
  PERFORM tap.login(tap.other_user());
  BEGIN PERFORM venue.get_signing_keys_door(v_s, v_dsid, v_secret, v_dev); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_keys_authenticated_direct', to_jsonb(v_err));
  BEGIN PERFORM venue.get_manifest_signing_context(); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('manifest_signing_context_authenticated', to_jsonb(v_err));
  -- the STAFF/CLIENT projection, unchanged (authenticated reads the table projection directly)
  INSERT INTO ev SELECT 'staff_m1_projection_row_keys', to_jsonb((SELECT array_agg(column_name::text ORDER BY column_name) FROM information_schema.column_privileges
     WHERE table_schema='kernel' AND table_name='signing_key' AND grantee='authenticated' AND privilege_type='SELECT'));
  BEGIN PERFORM kms_handle_ref FROM kernel.signing_key LIMIT 1; v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('staff_kms_handle_ref_read', to_jsonb(v_err));
  PERFORM tap.logout();

  SELECT ticket_atom_id INTO v_atom FROM venue.door_manifest_entry WHERE manifest_id = v_m1 ORDER BY serial_no LIMIT 1;
  PERFORM venue.append_door_manifest_delta(v_s, ARRAY[v_atom], 'revoke', gen_random_uuid());
  PERFORM tap.login(tap.other_user());
  INSERT INTO ev VALUES ('open_incremental_since_0', venue.get_door_manifest(v_s, 0));
  INSERT INTO ev VALUES ('open_incremental_since_1', venue.get_door_manifest(v_s, 1));
  PERFORM tap.logout();
  PERFORM tap.login_service();
  INSERT INTO ev VALUES ('door_incremental_since_0', venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0));
  INSERT INTO ev VALUES ('door_incremental_since_1', venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 1));
  INSERT INTO ev VALUES ('door_incremental_since_null', venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, NULL));
  -- wrong token / device / session / unknown id; service_role without credentials; the core directly
  BEGIN PERFORM venue.get_door_manifest_door(v_s, v_dsid, 'not-the-secret', v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_wrong_token', to_jsonb(v_err));
  BEGIN PERFORM venue.get_door_manifest_door(v_s, v_dsid, v_secret, gen_random_uuid(), 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_wrong_device', to_jsonb(v_err));
  BEGIN PERFORM venue.get_door_manifest_door(gen_random_uuid(), v_dsid, v_secret, v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_wrong_session', to_jsonb(v_err));
  BEGIN PERFORM venue.get_door_manifest_door(v_s, gen_random_uuid(), v_secret, v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_unknown_door_session_id', to_jsonb(v_err));
  BEGIN PERFORM venue.get_door_manifest_door(v_s, gen_random_uuid(), '', gen_random_uuid(), 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_service_role_no_credentials', to_jsonb(v_err));
  BEGIN PERFORM venue._get_door_manifest_core(v_s, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_core_direct_service_role', to_jsonb(v_err));
  PERFORM tap.logout();
  PERFORM tap.login_anon();
  BEGIN PERFORM venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_anon_direct_valid_credentials', to_jsonb(v_err));
  PERFORM tap.login(tap.other_user());
  BEGIN PERFORM venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_authenticated_direct_valid_credentials', to_jsonb(v_err));
  PERFORM tap.logout();

  -- unauthorized callers (error text captured, never a manifest)
  PERFORM tap.login(tap.buyer());
  BEGIN PERFORM venue.get_door_manifest(v_s, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('unauthorized_buyer', to_jsonb(v_err));
  PERFORM tap.login_service();
  BEGIN PERFORM venue.get_door_manifest(v_s, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('unauthorized_service_role_door_relay', to_jsonb(v_err));
  PERFORM tap.login(tap.other_user());
  BEGIN PERFORM venue.get_door_manifest(gen_random_uuid(), 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('wrong_session_unknown', to_jsonb(v_err));
  PERFORM tap.logout();

  -- closed
  PERFORM tap.login(tap.seller());
  PERFORM venue.close_door_manifest(v_s,'doors_closed','ev-c1');
  PERFORM tap.login(tap.other_user());
  INSERT INTO ev VALUES ('closed', venue.get_door_manifest(v_s, 0));
  PERFORM tap.logout();
  PERFORM tap.login_service();
  INSERT INTO ev VALUES ('door_closed', venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0));
  PERFORM tap.logout();

  -- expired: now() is frozen for this single transaction, so the stored window
  -- is backdated (guard trigger disabled for the fixture only) — the RPC can
  -- only be reading the STORED not_after.
  PERFORM tap.login(tap.seller());
  v_m2 := (venue.open_door_manifest(v_s,'doors_open','ev-d2') ->> 'manifest_id')::uuid;
  PERFORM tap.login(tap.other_user());
  INSERT INTO ev VALUES ('reopened_v2_fresh', venue.get_door_manifest(v_s, 0));
  PERFORM tap.logout();
  ALTER TABLE venue.door_manifest DISABLE TRIGGER tg_door_manifest_transition;
  UPDATE venue.door_manifest SET opened_at = now() - interval '3 hours', not_after = now() - interval '1 second' WHERE manifest_id = v_m2;
  ALTER TABLE venue.door_manifest ENABLE TRIGGER tg_door_manifest_transition;
  PERFORM tap.login(tap.other_user());
  INSERT INTO ev VALUES ('expired', venue.get_door_manifest(v_s, 0));
  PERFORM tap.logout();
  PERFORM tap.login_service();
  INSERT INTO ev VALUES ('door_expired', venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0));
  -- 114: no ACTIVE global key ⇒ the signing context is unavailable (fail closed); M1 still lists the key as rotating
  PERFORM tap.logout();   -- superuser flips the status (forward-only; the immutability guard permits active -> rotating)
  UPDATE kernel.signing_key SET status = 'rotating' WHERE key_id = v_g_active;
  PERFORM tap.login_service();
  INSERT INTO ev VALUES ('manifest_signing_context_no_active_global', venue.get_manifest_signing_context());
  INSERT INTO ev VALUES ('door_keys_after_rotation', venue.get_signing_keys_door(v_s, v_dsid, v_secret, v_dev));
  -- credentials invalidated BETWEEN the edge's admit check and the machine RPC
  INSERT INTO ev SELECT 'door_admit_check_before_revoke', jsonb_build_object('device_id', device_id, 'event_session_id', event_session_id)
    FROM kernel.assert_door_session(v_dev, v_s, v_dsid, v_secret);
  PERFORM tap.login(tap.seller());   -- venue_manager revokes
  PERFORM venue.revoke_door_session(v_dsid, 'operator_revoked', 'ev-rv');
  PERFORM tap.login_service();
  BEGIN PERFORM venue.get_door_manifest_door(v_s, v_dsid, v_secret, v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_revoked_between_checks', to_jsonb(v_err));
  -- expired door session (fresh mint, expiry backdated — door_session has no guard trigger)
  v_mint2 := venue.mint_door_session(v_venue, v_s, v_dev, 'pin-ev', 'ev-mint2');
  PERFORM tap.logout();
  UPDATE venue.door_session SET issued_at = now() - interval '3 hours', expires_at = now() - interval '1 second' WHERE door_session_id = (v_mint2 ->> 'door_session_id')::uuid;
  PERFORM tap.login_service();
  BEGIN PERFORM venue.get_door_manifest_door(v_s, (v_mint2 ->> 'door_session_id')::uuid, v_mint2 ->> 'secret', v_dev, 0); v_err := 'NO ERROR'; EXCEPTION WHEN OTHERS THEN v_err := SQLSTATE || ' ' || SQLERRM; END;
  INSERT INTO ev VALUES ('door_expired_door_session', to_jsonb(v_err));
  PERFORM tap.logout();
  INSERT INTO ev SELECT 'expired_stored_row', jsonb_build_object('status', status, 'not_after', not_after, 'now', now()) FROM venue.door_manifest WHERE manifest_id = v_m2;
  INSERT INTO ev VALUES ('rpc_source', jsonb_build_object('definition_md5', md5(pg_get_functiondef('venue.get_door_manifest(uuid,integer)'::regprocedure)),
     'door_definition_md5', md5(pg_get_functiondef('venue.get_door_manifest_door(uuid,uuid,text,uuid,integer)'::regprocedure)),
     'core_definition_md5', md5(pg_get_functiondef('venue._get_door_manifest_core(uuid,integer)'::regprocedure)),
     'captured_at', now(), 'database', current_database()));
END
$body$;
SELECT jsonb_pretty(jsonb_object_agg(k, v)) FROM ev;
ROLLBACK;
