-- 060_auth_password_change_notifications.sql   APPLIED 2026-08-05, verified.
-- (applied as 060 + 060b)
--
-- Password-change inbox notifications via a watermark sweep of
-- auth.audit_log_entries. No trigger is added to the auth schema: GoTrue owns
-- it and recreates objects across platform upgrades, and an error in such a
-- trigger would abort signup and login.
--
-- EMAIL CHANGE IS DELIBERATELY NOT SHIPPED. Empirical verdict, five lines of
-- evidence: all 3 `user_modified` rows in production have `traits` entirely
-- absent (no key to test); email change has never been exercised here (14/14
-- users have email_change_sent_at NULL, confirm_status 0); GoTrue in this
-- project has never emitted an email-change-specific action; profiles has no
-- email column to diff against; and every observed `user_modified` was
-- something else -- one a password-reset side-effect firing 0.76ms later, two
-- post-login metadata updates. Shipping on `user_modified` would have produced
-- a 100% false-positive rate: three bogus "your email was changed" security
-- alerts and zero true ones. A false security alert is worse than none.
-- If wanted later, the sound path is a separate sha256(auth.users.email)
-- mirror sweep -- true positives, no guessing, no PII duplicated outside auth.
--
-- DESIGN NOTES
--  * floor_at and watermark are seeded to now() in the same statement that
--    creates the row, and v_lower = greatest(watermark - lookback, floor_at),
--    so the first run cannot reach a historical row. No backfill, by construction.
--  * dedupe_key = 'auth_pwd:' || <audit row uuid>. The audit id is immutable and
--    unique, so the 60-minute overlap re-presents the same key every run and
--    notifications_dedupe_key_uidx absorbs it. Correctness does not depend on
--    the advisory lock.
--  * The 60-minute overlap is mandatory: created_at is GoTrue's application
--    clock, not commit time, so a row stamped T can become visible later.
--    postgres can neither own nor index auth.audit_log_entries (not superuser),
--    so the scan is a seq scan regardless -- widening the window costs no I/O.
--    Measured 17.5ms over 2,489 rows. Revisit past ~500k rows.
--  * Zero-uuid actor excluded explicitly: admin/service_role-initiated resets
--    carry '00000000-...' and a row with that id genuinely exists in auth.users,
--    so a join alone would not filter it.
--  * Inner join auth.users: some audit rows reference deleted users, and
--    notifications.user_id has FK -> auth.users ON DELETE CASCADE.
--  * The watermark advances only on the success path, so a failure retries the
--    window rather than dropping events.
--  * postgres already holds SELECT WITH GRANT OPTION on auth.audit_log_entries
--    from supabase_auth_admin -- no new grant needed. service_role canNOT read
--    it, so this must not be routed through an edge function.
--
-- 060b fixed a real bug the sweep's own error handler caught on first run: the
-- batch was a bare SELECT inside plpgsql ("query has no destination for result
-- data"). It recorded last_error and left the watermark unadvanced, so nothing
-- was skipped. Now SELECT count(*) INTO, which also supplies the row count.
--
-- VERIFIED: clean run on the empty window; temporarily lowering the barrier
-- past the one historical user_updated_password row produced exactly 1
-- notification; replaying produced still exactly 1 (idempotent); correct type
-- and link. Test row deleted and the barrier reset to now() afterwards.
-- Scheduled: sweep-auth-password-changes @ */5 * * * *, active.
--
-- CAVEAT: only one user_updated_password row exists in production and it is the
-- recovery-link path. The authenticated-change path is inferred from the
-- dedicated action name, not observed. Copy deliberately does not assert which
-- path was used.
--
-- Rollback: supabase/rollbacks/060_auth_password_change_notifications_rollback.sql
