#!/usr/bin/env python3
"""Emit the supabase_migrations.schema_migrations row for a migration file, with the REAL
statement array (top-level split on ';' outside single-quoted strings and -- comments;
comment-only chunks dropped; BEGIN/COMMIT kept). usage: ledger-row.py <file> > ledger.sql"""
import re, sys, pathlib
path = pathlib.Path(sys.argv[1]); src = path.read_text()
m = re.match(r'(\d{14}|\d{3})_(.+)\.sql$', path.name); version, name = m.group(1), m.group(2)
stmts, buf, i, n, in_str, in_cmt = [], [], 0, len(src), False, False
while i < n:
    c = src[i]
    if in_cmt:
        if c == '\n': in_cmt = False
        i += 1; continue
    if in_str:
        buf.append(c)
        if c == "'":
            if i + 1 < n and src[i+1] == "'": buf.append("'"); i += 2; continue
            in_str = False
        i += 1; continue
    if c == '-' and src.startswith('--', i): in_cmt = True; i += 2; continue
    if c == "'": in_str = True; buf.append(c); i += 1; continue
    if c == ';':
        s = ''.join(buf).strip()
        if s: stmts.append(s + ';')
        buf = []; i += 1; continue
    buf.append(c); i += 1
tail = ''.join(buf).strip()
if tail: stmts.append(tail)
assert '$stmt$' not in src
arr = ',\n  '.join(f'$stmt${s}$stmt$' for s in stmts)
print(f"-- ledger row for {path.name}: {len(stmts)} statements (generated by ledger-row.py; do not hand-edit)")
print("insert into supabase_migrations.schema_migrations (version, name, statements)\nvalues (")
print(f"  '{version}', '{name}',\n  array[\n  {arr}\n  ]::text[]\n) on conflict (version) do nothing;")
print(f"select version, name, array_length(statements, 1) as statements, length(array_to_string(statements, E'\\n')) as chars\n  from supabase_migrations.schema_migrations where version = '{version}';")
